name: Build and Push Docker Images

on:
  push:
    branches:
      - branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY 
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 064686496891.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push MySQL Docker Image
        run: |
          cd database
          docker build -t my-mysql-image .
          docker tag my-mysql-image:latest 064686496891.dkr.ecr.us-east-1.amazonaws.com/my-mysql-image:latest
          docker push 064686496891.dkr.ecr.us-east-1.amazonaws.com/my-mysql-image:latest

      - name: Build and Push Application Docker Image
        run: |
          cd ../app
          docker build -t my-app-image .
          docker tag my-app-image:latest 064686496891.dkr.ecr.us-east-1.amazonaws.com/my-app-image:latest
          docker push 064686496891.dkr.ecr.us-east-1.amazonaws.com/my-app-image:latest
