name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1  # AWS action to simplify login
        with:
          region: us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
       
      - name: Build and Push MySQL Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd database
          docker build -t my-mysql-image .
          docker tag my-mysql-image:latest $ECR_REGISTRY/my-mysql-image:latest
          docker push $ECR_REGISTRY/my-mysql-image:latest

      # Step 4: Build and Push Application Docker Image
      - name: Build and Push Application Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd ../app
          docker build -t my-app-image .
          docker tag my-app-image:latest $ECR_REGISTRY/my-app-image:latest
          docker push $ECR_REGISTRY/my-app-image:latest
